name: sklearn-env
channels:
  - conda-forge
dependencies:
  - python=3.10.0
  - pip
  - pip:
    - numpy
    - scikit-learn
    - scipy
    - pandas
    - matplotlib
    - inference-schema[numpy-support]
    - xlrd
    - mlflow
    - azureml-mlflow
    - azureml-defaults
    - azureml-core
    - azureml-telemetry
    - requests
    - datasets
    - jobtools
    - cloudpickle
    - dask
